"""SAP standard data dictionary — the technical ground truth for every field.

Three layers, resolved in this order by :func:`get_dictionary`:

1. **ABAP DDIC bundle** (``sap/dictionaries/ecc6/``) — SAP ECC 6.0 standard
   tables, fields, keys, data elements, domains, ABAP types, lengths,
   decimals, check tables, conversion exits, lowercase flags and domain fixed
   values, generated by ``scripts/build_ddic_bundle.py``. Never hand-edited.
2. **S/4HANA delta** (``sap/dictionaries/s4hana_delta.yaml``) — SAP's
   documented simplifications applied on top of ECC (e.g. MATNR → CHAR 40,
   SD status fields moved from VBUK/VBUP into VBAK/VBAP). S/4 is therefore
   always "ECC + explicit, cited differences", never a second hand-kept copy.
3. **Canonical schemas** (``sap/dictionaries/canonical/*.yaml``) — Meridian's
   flattened views over non-ABAP systems (SuccessFactors OData, Concur,
   Ariba, GRC, MDG, fleet). Each field names its source entity/property.

A live DDIC snapshot read from a connected system (Phase 1) always wins over
these bundles; every lookup result carries ``provenance`` so callers can say
where a decision came from.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, replace
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Optional

import yaml

_ROOT = Path(__file__).resolve().parent / "dictionaries"
_CLIENT_FIELDS = {"MANDT", "CLIENT", "RCLNT"}

# sap_systems.system_type → dictionary release
RELEASE_FOR_SYSTEM = {
    "ecc": "ecc6",
    "ewm": "ecc6",
    "ewms": "ecc6",
    "s4hana_onprem": "s4hana",
    "s4hana_cloud": "s4hana",
    "s4hana": "s4hana",
}


@dataclass(frozen=True)
class FixedValue:
    low: str
    high: Optional[str]
    text: str


@dataclass(frozen=True)
class Field:
    table: str
    name: str
    key: bool
    type: Optional[str]              # ABAP DDIC type: CHAR, NUMC, DATS, DEC, CURR, QUAN, ...
    length: int
    decimals: int = 0
    data_element: Optional[str] = None
    domain: Optional[str] = None
    description: str = ""
    check_table: Optional[str] = None
    check_field: Optional[str] = None    # column of check_table holding the allowed values
    conversion_exit: Optional[str] = None
    lowercase: bool = False
    fixed_values: tuple[FixedValue, ...] = ()
    source: Optional[str] = None     # canonical schemas: "Entity.property"
    picklist: Optional[str] = None   # SuccessFactors picklist id (tenant-configurable values)
    provenance: str = "sap_standard"

    @property
    def qualified(self) -> str:
        return f"{self.table}.{self.name}"

    @property
    def check_ref(self) -> Optional[str]:
        """``CHECKTABLE.FIELD`` whose values are the allowed values, if known."""
        return f"{self.check_table}.{self.check_field}" if self.check_table and self.check_field else None

    def allowed_values(self) -> Optional[set[str]]:
        """Domain fixed values (single values only), or None if the domain is open."""
        if not self.fixed_values or any(v.high for v in self.fixed_values):
            return None
        return {v.low for v in self.fixed_values}


@dataclass(frozen=True)
class Table:
    name: str
    description: str
    fields: dict[str, Field]
    keys: tuple[str, ...]            # business key, client field excluded
    category: str = "TRANSP"
    foreign_keys: tuple[dict, ...] = ()
    obsolete_in: Optional[str] = None  # e.g. "s4hana" with a replacement note
    note: Optional[str] = None
    provenance: str = "sap_standard"


@dataclass
class Dictionary:
    release: str
    tables: dict[str, Table] = field(default_factory=dict)

    def table(self, name: str) -> Optional[Table]:
        return self.tables.get(name.upper())

    def field(self, table: str, name: str) -> Optional[Field]:
        t = self.table(table)
        return t.fields.get(name.upper()) if t else None

    def resolve(self, qualified: str) -> Optional[Field]:
        """Resolve ``TABLE.FIELD``; None if either part is unknown."""
        if "." not in qualified:
            return None
        table, name = qualified.split(".", 1)
        return self.field(table, name)

    def keys(self, table: str) -> tuple[str, ...]:
        t = self.table(table)
        return t.keys if t else ()


# ── Loading ──────────────────────────────────────────────────────────────────


@lru_cache(maxsize=None)
def _domain(release_dir: str, name: str) -> Optional[dict]:
    p = _ROOT / release_dir / "domains" / f"{name.replace('/', '_')}.json"
    return json.loads(p.read_text()) if p.exists() else None


@lru_cache(maxsize=1)
def _check_overrides() -> dict[str, dict]:
    p = _ROOT / "check_tables.yaml"
    return yaml.safe_load(p.read_text()) or {} if p.exists() else {}


def _abap_table(path: Path, release_dir: str) -> Table:
    raw = json.loads(path.read_text())
    fields: dict[str, Field] = {}
    fk = {(k["field"], k["foreign_table"]): k["foreign_field"] for k in raw.get("foreign_keys", [])}
    for f in raw["fields"]:
        dom = _domain(release_dir, f["domain"]) if f.get("domain") else None
        check_table = f.get("check_table") or (dom or {}).get("value_table")
        check_field = fk.get((f["name"], check_table)) if check_table else None
        override = _check_overrides().get(f"{raw['table']}.{f['name']}")
        if override:
            check_table, check_field = override["table"], override["field"]
        elif check_table == "*":
            check_table = None
        fields[f["name"]] = Field(
            table=raw["table"],
            name=f["name"],
            key=bool(f["key"]),
            type=f.get("type"),
            length=int(f.get("length") or 0),
            decimals=int(f.get("decimals") or 0),
            data_element=f.get("data_element"),
            domain=f.get("domain"),
            description=f.get("description", ""),
            check_table=check_table,
            check_field=check_field,
            conversion_exit=(dom or {}).get("conversion_exit"),
            lowercase=bool((dom or {}).get("lowercase")),
            fixed_values=tuple(
                FixedValue(v["low"], v.get("high"), v.get("text", ""))
                for v in (dom or {}).get("fixed_values", [])
            ),
        )
    keys = tuple(n for n, f in fields.items() if f.key and n not in _CLIENT_FIELDS)
    return Table(
        name=raw["table"],
        description=raw.get("description", ""),
        fields=fields,
        keys=keys,
        category=raw.get("category", "TRANSP"),
        foreign_keys=tuple(raw.get("foreign_keys", [])),
    )


def _canonical_tables() -> Iterable[Table]:
    for path in sorted((_ROOT / "canonical").glob("*.yaml")):
        doc = yaml.safe_load(path.read_text())
        system = doc["system"]
        for tname, t in (doc.get("tables") or {}).items():
            fields = {
                fname.upper(): Field(
                    table=tname.upper(),
                    name=fname.upper(),
                    key=fname.upper() in {k.upper() for k in t.get("keys", [])},
                    type=f.get("type", "CHAR"),
                    length=int(f.get("length", 0)),
                    decimals=int(f.get("decimals", 0)),
                    description=f.get("description", ""),
                    check_table=f.get("check_table"),
                    check_field=f.get("check_field") or ("externalCode" if f.get("check_table") else None),
                    picklist=f.get("picklist"),
                    lowercase=bool(f.get("lowercase", True)),
                    fixed_values=tuple(FixedValue(str(v), None, "") for v in f.get("values", [])),
                    source=f.get("source"),
                    provenance=f"canonical:{system}",
                )
                for fname, f in (t.get("fields") or {}).items()
            }
            yield Table(
                name=tname.upper(),
                description=t.get("description", ""),
                fields=fields,
                keys=tuple(k.upper() for k in t.get("keys", [])),
                category="VIEW",
                note=t.get("source"),
                provenance=f"canonical:{system}",
            )


def _apply_s4_delta(tables: dict[str, Table]) -> dict[str, Table]:
    delta = yaml.safe_load((_ROOT / "s4hana_delta.yaml").read_text())
    domain_len = {d.upper(): v for d, v in (delta.get("domain_length") or {}).items()}
    out: dict[str, Table] = {}
    for name, t in tables.items():
        fields = {
            n: replace(f, length=domain_len[f.domain]["length"], provenance="sap_standard+s4_delta")
            if f.domain and f.domain.upper() in domain_len else f
            for n, f in t.fields.items()
        }
        out[name] = replace(t, fields=fields)

    for tname, moves in (delta.get("fields_moved") or {}).items():
        t = out.get(tname)
        if not t:
            continue
        fields = dict(t.fields)
        for fname, origin in moves["fields"].items():
            src = out.get(origin.split(".")[0])
            src_f = src.fields.get(origin.split(".")[1]) if src else None
            if src_f:
                fields[fname] = replace(src_f, table=tname, name=fname, key=False,
                                        provenance="sap_standard+s4_delta")
        out[tname] = replace(t, fields=fields)

    for tname, info in (delta.get("obsolete_tables") or {}).items():
        if tname in out:
            out[tname] = replace(out[tname], obsolete_in="s4hana", note=info.get("replaced_by"))
    return out


@lru_cache(maxsize=None)
def get_dictionary(release: str = "ecc6") -> Dictionary:
    """Load a dictionary release: ``ecc6`` or ``s4hana`` (plus canonical schemas)."""
    release = RELEASE_FOR_SYSTEM.get(release, release)
    if release not in ("ecc6", "s4hana"):
        raise ValueError(f"Unknown dictionary release: {release}")
    tables = {p.stem: _abap_table(p, "ecc6") for p in sorted((_ROOT / "ecc6" / "tables").glob("*.json"))}
    if release == "s4hana":
        tables = _apply_s4_delta(tables)
    for t in _canonical_tables():
        tables[t.name] = t  # an explicitly declared canonical view wins over a same-named ABAP object
    return Dictionary(release=release, tables=tables)


def dictionary_for_system(system_type: str) -> Dictionary:
    return get_dictionary(RELEASE_FOR_SYSTEM.get(system_type, "ecc6"))
