"""Generated by checks/country_rules.py from the system's T005 / BNKA."""

import pandas as pd

from checks.base import BaseCheck, Evaluation, is_blank
from checks.country_rules import violates


class CountryFormatCheck(BaseCheck):
    check_class = "country_format_check"

    def columns(self) -> list[str]:
        cols = [self.rule["field"], self.rule["country_field"]]
        return cols + ([self.rule["street_field"]] if self.rule.get("street_field") else [])

    def evaluate(self, df: pd.DataFrame) -> Evaluation:
        r = self.rule
        value = df[r["field"]].astype("string").str.strip().fillna("")
        country = df[r["country_field"]].astype("string").str.strip().fillna("")
        if r["family"] == "format":
            specs = {c: (int(s[0]), str(s[1])) for c, s in r["specs"].items()}
            population = value.ne("") & country.isin(specs.keys())
            failing = pd.Series([population.at[i] and violates(value.at[i], *specs[country.at[i]])
                                 for i in df.index], index=df.index, dtype=bool)
            return Evaluation(population, failing, {"country_rules": "T005"}, invalid_values_field=r["field"])
        if r["family"] == "required":
            street = ~is_blank(df[r["street_field"]])
            population = country.isin(r["countries"]) & street
            return Evaluation(population, value.eq(""), {"countries_requiring_postal_code": len(r["countries"])})
        keys = set(r["keys"])
        population = value.ne("") & country.isin(r["countries"])
        return Evaluation(population, ~(country + "|" + value).isin(keys), {"bank_directory": "BNKA"},
                          invalid_values_field=r["field"])
