"""Generated by checks/value_placement.py: misplaced content, placeholders,
postal-code/city swaps, and records declared dead only in text."""

import pandas as pd

from checks.base import BaseCheck, Evaluation, as_of_time, is_blank
from checks.types.domain_value_check import _parse_dates
from checks.value_placement import (_CITY_WITH_CODE, _POSTCODE_ONLY, DETECTORS, FOREIGN, TARGET, is_placeholder,
                                    status_markers)


def _text(df: pd.DataFrame, col: str) -> pd.Series:
    # object dtype: Python regex (backreferences), not the Arrow engine
    return df[col].astype("string").str.strip().fillna("").astype(object)


class ValuePlacementCheck(BaseCheck):
    check_class = "value_placement_check"

    def columns(self) -> list[str]:
        if self.rule["family"] == "status_text":  # the primary name + one block flag must be there; the rest if extracted
            return [self.rule["fields"][0], self.rule["block_fields"][0]]
        return super().columns()

    def evaluate(self, df: pd.DataFrame) -> Evaluation | None:
        family = self.rule["family"]
        if family == "misplaced":
            s = _text(df, self.rule["field"])
            populated = s.ne("")
            found = pd.Series("", index=df.index, dtype="string")
            for name in FOREIGN[self.rule["kind"]]:
                hit = populated & found.eq("") & DETECTORS[name](s.where(populated, "")).fillna(False).astype(bool)
                found = found.mask(hit, name)
            failing = found.ne("")
            counts = found[failing].value_counts().to_dict()
            return Evaluation(populated, failing, {
                "detected": {k: int(v) for k, v in counts.items()},
                "belongs_in": {k: TARGET[k] for k in counts},
            }, invalid_values_field=self.rule["field"])
        if family == "placeholder":
            s = _text(df, self.rule["field"])
            populated = s.ne("")
            return Evaluation(populated, populated & is_placeholder(s, self.rule["kind"]),
                              invalid_values_field=self.rule["field"])
        if family == "swap":
            pc_col, city_col = self.rule["fields"]
            pc, city = _text(df, pc_col), _text(df, city_col)
            city_in_pc = pc.ne("") & ~pc.str.contains(r"\d") & pc.str.count(r"[A-Za-z]").ge(3)
            pc_in_city = city.ne("") & (city.str.fullmatch(_POSTCODE_ONLY) | city.str.contains(_CITY_WITH_CODE))
            failing = (city_in_pc | pc_in_city).fillna(False)
            return Evaluation(pc.ne("") | city.ne(""), failing, {
                "city_in_postal_code": int(city_in_pc.sum()), "postal_code_in_city": int(pc_in_city.sum())})
        if family == "status_text":
            marked = pd.Series(False, index=df.index)
            for c in (c for c in self.rule["fields"] if c in df.columns):
                marked |= status_markers(_text(df, c))
            blocked = pd.Series(False, index=df.index)
            for c in (c for c in self.rule["block_fields"] if c in df.columns):
                blocked |= _text(df, c).ne("")
            return Evaluation(pd.Series(True, index=df.index), marked & ~blocked,
                              {"marked_in_text": int(marked.sum()), "marked_and_blocked": int((marked & blocked).sum())})
        if family == "vat_checksum":
            from checks.value_placement import vat_status
            s = _text(df, self.rule["field"])
            st = s.map(lambda v: vat_status(v) if v else "n/a")
            return Evaluation(st.ne("n/a"), st.eq("bad"), invalid_values_field=self.rule["field"])
        if family == "date_range":
            d = _parse_dates(df[self.rule["field"]])
            populated = ~is_blank(df[self.rule["field"]])
            today = as_of_time(self.rule.get("_as_of")).normalize() + pd.Timedelta(days=1)  # snapshot date, else now
            return Evaluation(populated & d.notna(), (d < pd.Timestamp("1970-01-01")) | (d > today),
                              invalid_values_field=self.rule["field"])
        if family == "change_before_create":
            created, changed = (_parse_dates(df[c]) for c in self.rule["fields"])
            both = created.notna() & changed.notna()
            return Evaluation(both, changed < created)
        return None
