/**
 * Meridian Install Worker
 *
 * Restores the hosted one-liner installer:
 *   curl -fsSL "https://get.meridian.vantax.co.za/install?key=MRDX-..." | sudo bash
 *
 * Routes:
 *   GET /install?key=<licence>[&tier=&domain=&admin_email=&admin_password=]
 *       Validates the licence, then returns a bootstrap shell script with the
 *       GHCR token injected server-side. Key-gated.
 *   GET /files/<allowlisted-repo-path>
 *       Proxies a deploy file from the private repo via the GitHub Contents API
 *       (server-side REPO_TOKEN). Non-secret templates only.
 *   GET /  → short human-readable usage note.
 */

export interface Env {
  // secrets
  GHCR_TOKEN: string;   // read:packages PAT — injected into the returned script
  REPO_TOKEN: string;   // repo contents:read PAT — used to proxy deploy files
  // vars
  GHCR_USER: string;
  IMAGE_PREFIX: string;
  LICENCE_VALIDATE_URL: string;
  LICENCE_SERVER_BASE: string;
  REPO: string;
  REPO_REF: string;
}

// Files the bootstrap is allowed to fetch via /files/<path>. Anything not on
// this list is rejected, so the proxy can't be used to exfiltrate the repo.
const ALLOWED_FILES = new Set<string>([
  "scripts/meridian-deploy.sh",
  "scripts/update.sh",
  "docker/docker-compose.customer.yml",
  "docker/docker-compose.customer.ollama.yml",
  "docker/nginx/meridian.conf",
]);

const LICENCE_KEY_RE = /^MRDX-[A-F0-9]{8}-[A-F0-9]{8}-[A-F0-9]{8}$/;

function hex(bytes: number): string {
  const a = new Uint8Array(bytes);
  crypto.getRandomValues(a);
  return Array.from(a, (b) => b.toString(16).padStart(2, "0")).join("");
}

function text(body: string, status = 200, contentType = "text/plain; charset=utf-8"): Response {
  return new Response(body, { status, headers: { "content-type": contentType } });
}

async function validateLicence(key: string, env: Env): Promise<boolean> {
  try {
    const r = await fetch(env.LICENCE_VALIDATE_URL, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ licenceKey: key, machineFingerprint: "install-worker" }),
    });
    if (r.status !== 200) return false;
    const j = (await r.json()) as { valid?: boolean };
    return j.valid === true;
  } catch {
    return false;
  }
}

/** Build a pre-configured .env whose keys match meridian-deploy.sh's
 *  PRECONFIGURED path (it greps DATABASE_URL/DB_PASSWORD to detect it). */
function buildEnv(
  key: string,
  tier: string,
  domain: string,
  adminEmail: string,
  adminPassword: string,
  env: Env,
): string {
  const dbPass = hex(16);
  const appPass = hex(16);
  const minioPass = hex(16);
  const credKey = hex(32);

  const llm =
    tier === "2"
      ? "LLM_PROVIDER=ollama\nOLLAMA_BASE_URL=http://ollama:11434\nOLLAMA_MODEL=qwen3.5:9b-instruct"
      : "LLM_PROVIDER=none";

  return [
    "# Meridian .env — generated by install-worker",
    "MERIDIAN_LICENCE_MODE=online",
    `MERIDIAN_LICENCE_KEY=${key}`,
    `MERIDIAN_LICENCE_SERVER_URL=${env.LICENCE_SERVER_BASE}`,
    "",
    "# Image registry — baked deploy credentials (customer supplies nothing)",
    `MERIDIAN_GHCR_USER=${env.GHCR_USER}`,
    `MERIDIAN_GHCR_TOKEN=${env.GHCR_TOKEN}`,
    "MERIDIAN_IMAGE_SOURCE=ghcr",
    "",
    `# LLM (Tier ${tier})`,
    llm,
    "",
    "# Deployment",
    `SERVER_DOMAIN=${domain}`,
    "SSL_MODE=1",
    "WORKER_LANE=all",
    `ADMIN_EMAIL=${adminEmail}`,
    "ADMIN_NAME=Admin",
    `ADMIN_PASSWORD=${adminPassword}`,
    "",
    "INTERNAL_API_URL=http://api:8000",
    "",
    "# Database",
    `DB_PASSWORD=${dbPass}`,
    `MERIDIAN_APP_PASSWORD=${appPass}`,
    `DATABASE_URL=postgresql+asyncpg://meridian_app:${appPass}@db:5432/meridian`,
    `DATABASE_URL_SYNC=postgresql://meridian_app:${appPass}@db:5432/meridian`,
    `DATABASE_URL_MIGRATE=postgresql://meridian:${dbPass}@db:5432/meridian`,
    "",
    "REDIS_URL=redis://redis:6379/0",
    "",
    "MINIO_ACCESS_KEY=meridian",
    `MINIO_PASSWORD=${minioPass}`,
    `MINIO_SECRET_KEY=${minioPass}`,
    "MINIO_BUCKET_UPLOADS=meridian-uploads",
    "MINIO_BUCKET_REPORTS=meridian-reports",
    "",
    "AUTH_MODE=local",
    "NEXT_PUBLIC_AUTH_MODE=local",
    "",
    "SAP_CONNECTOR=mock",
    `CREDENTIAL_MASTER_KEY=${credKey}`,
    "",
  ].join("\n");
}

/** The bootstrap script returned by /install. Runs non-interactively so it can
 *  be piped straight to `sudo bash`. */
function buildBootstrap(origin: string, tier: string, envFile: string, adminEmail: string, adminPassword: string): string {
  const overlay =
    tier === "2"
      ? 'get docker/docker-compose.customer.ollama.yml\n'
      : "";
  return `#!/usr/bin/env bash
set -euo pipefail
DIR=/opt/meridian
BASE="${origin}"

echo "→ Installing Meridian into $DIR"
sudo mkdir -p "$DIR/scripts" "$DIR/docker/nginx"

# Pre-configured .env (licence + GHCR token + generated secrets) — written
# locally, never printed. meridian-deploy.sh runs in PRECONFIGURED mode off it.
sudo tee "$DIR/.env" >/dev/null <<'MERIDIAN_ENV'
${envFile}MERIDIAN_ENV
sudo cp "$DIR/.env" "$DIR/docker/.env"
sudo chmod 600 "$DIR/.env" "$DIR/docker/.env"

# Fetch deploy files from the installer host (no repo clone, no token).
# get() auto-creates the destination subdir so nested paths (docker/nginx/…) work.
get() { sudo mkdir -p "$DIR/$(dirname "$1")"; curl -fsSL "$BASE/files/$1" | sudo tee "$DIR/$1" >/dev/null && echo "  got $1"; }
get scripts/meridian-deploy.sh
get docker/docker-compose.customer.yml
get docker/nginx/meridian.conf
${overlay}
cd "$DIR"
sudo bash scripts/meridian-deploy.sh --non-interactive

echo ""
echo "════════════════════════════════════════════════"
echo "  Meridian installed."
echo "  Admin login: ${adminEmail} / ${adminPassword}"
echo "  (change it immediately after first sign-in)"
echo "════════════════════════════════════════════════"
`;
}

async function serveFile(path: string, env: Env): Promise<Response> {
  if (!ALLOWED_FILES.has(path)) return text("Not found", 404);
  const url = `https://api.github.com/repos/${env.REPO}/contents/${path}?ref=${env.REPO_REF}`;
  const r = await fetch(url, {
    headers: {
      Authorization: `token ${env.REPO_TOKEN}`,
      Accept: "application/vnd.github.raw",
      "User-Agent": "meridian-install-worker",
    },
  });
  if (!r.ok) return text(`Could not fetch ${path} (HTTP ${r.status})`, 502);
  return new Response(r.body, { status: 200, headers: { "content-type": "text/plain; charset=utf-8" } });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/" || url.pathname === "") {
      return text(
        "Meridian installer.\n\n" +
          '  curl -fsSL "https://get.meridian.vantax.co.za/install?key=MRDX-XXXXXXXX-XXXXXXXX-XXXXXXXX" | sudo bash\n\n' +
          "Optional query params: tier (0|2), domain, admin_email, admin_password.\n",
      );
    }

    if (url.pathname.startsWith("/files/")) {
      return serveFile(url.pathname.slice("/files/".length), env);
    }

    if (url.pathname === "/install") {
      const key = (url.searchParams.get("key") || "").trim().toUpperCase();
      if (!key) return text("# error: missing ?key=<licence>\n", 400, "text/x-shellscript");
      if (!LICENCE_KEY_RE.test(key)) {
        return text("# error: invalid licence key format (expected MRDX-XXXXXXXX-XXXXXXXX-XXXXXXXX)\n", 400, "text/x-shellscript");
      }
      if (!(await validateLicence(key, env))) {
        return text("# error: licence validation failed — contact support@vantax.co.za\n", 403, "text/x-shellscript");
      }

      const tier = (url.searchParams.get("tier") || "0").trim();
      const domain = (url.searchParams.get("domain") || "localhost").trim();
      const adminEmail = (url.searchParams.get("admin_email") || `admin@${domain}`).trim();
      const adminPassword = (url.searchParams.get("admin_password") || hex(12)).trim();

      const envFile = buildEnv(key, tier, domain, adminEmail, adminPassword, env);
      const script = buildBootstrap(url.origin, tier, envFile, adminEmail, adminPassword);
      return text(script, 200, "text/x-shellscript; charset=utf-8");
    }

    return text("Not found", 404);
  },
};
