#!/usr/bin/env bash
# =========================================================
# Build the SAP RFC overlay images from the SAP NW RFC SDK on THIS host.
#
#   sudo bash scripts/build-rfc-overlay.sh [--sdk /usr/local/sap/nwrfcsdk]
#
# Produces meridian-api:rfc-local and meridian-worker:rfc-local on top of the
# currently pulled :latest images and writes docker-compose.rfc.yml (next to the
# customer compose file) so
# api, worker and beat run them. scripts/update.sh re-runs this after every
# pull while that file exists, so an update never drops RFC support.
# =========================================================
set -euo pipefail

SDK="${SAPNWRFC_HOME:-/usr/local/sap/nwrfcsdk}"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --sdk) SDK="$2"; shift 2 ;;
        -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "Unknown flag: $1" >&2; exit 2 ;;
    esac
done

die() { echo "[ERROR] $*" >&2; exit 1; }
[[ -f "$SDK/lib/libsapnwrfc.so" ]] || die "SAP NW RFC SDK not found at $SDK (expected lib/libsapnwrfc.so). Pass --sdk <dir>."
[[ -d "$SDK/include" ]] || die "$SDK/include missing — the SDK's headers are needed to build PyRFC."

cd "$(dirname "$0")/.."
if [[ -f "docker/docker-compose.customer.yml" ]]; then COMPOSE_DIR=docker; else COMPOSE_DIR=.; fi
OVERLAY="${COMPOSE_DIR}/docker-compose.rfc.yml"
CTX=$(mktemp -d)
trap 'rm -rf "$CTX"' EXIT
cp -a "$SDK" "$CTX/nwrfcsdk"
cp docker/Dockerfile.rfc "$CTX/Dockerfile"

for svc in api worker; do
    base="ghcr.io/vantax-org/meridian-${svc}:latest"
    docker image inspect "$base" >/dev/null 2>&1 || die "$base not present — pull it first (docker compose pull)."
    echo "[INFO] Building meridian-${svc}:rfc-local from $base ..."
    docker build --build-arg BASE_IMAGE="$base" -t "meridian-${svc}:rfc-local" "$CTX"
done

cat > "$OVERLAY" <<'YML'
# Generated by scripts/build-rfc-overlay.sh — SAP RFC (NW RFC SDK + PyRFC) images built on this host.
services:
  api:
    image: meridian-api:rfc-local
  worker:
    image: meridian-worker:rfc-local
  beat:
    image: meridian-worker:rfc-local
YML
echo "[INFO] RFC overlay ready. Apply with:"
echo "       sudo bash scripts/update.sh   (or: docker compose -f <compose file> -f $OVERLAY up -d api worker beat)"
