apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meridian.fullname" . }}-config
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
data:
  LLM_PROVIDER: {{ .Values.llm.provider | quote }}
  OLLAMA_BASE_URL: "http://{{ include "meridian.fullname" . }}-llm:11434"
  OLLAMA_MODEL: {{ .Values.llm.model | quote }}
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgres.user }}:$(DB_PASSWORD)@{{ include "meridian.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
  DATABASE_URL_SYNC: "postgresql://{{ .Values.postgres.user }}:$(DB_PASSWORD)@{{ include "meridian.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
  REDIS_URL: "redis://{{ include "meridian.fullname" . }}-redis:6379/0"
  MINIO_ENDPOINT: "{{ include "meridian.fullname" . }}-minio:9000"
  MINIO_ACCESS_KEY: "meridian"
  MINIO_BUCKET_UPLOADS: "meridian-uploads"
  MINIO_BUCKET_REPORTS: "meridian-reports"
  LICENCE_SERVER_URL: {{ .Values.licence.serverUrl | quote }}
  AUTH_MODE: {{ .Values.auth.mode | quote }}
