apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meridian.fullname" . }}-frontend
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      {{- include "meridian.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "meridian.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.frontend }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: INTERNAL_API_URL
              value: "http://{{ include "meridian.fullname" . }}-api:8000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
