apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "meridian.fullname" . }}-api
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "meridian.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
