apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meridian.fullname" . }}-secret
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioPassword | b64enc | quote }}
  LICENCE_KEY: {{ .Values.licence.key | b64enc | quote }}
  {{- if .Values.secrets.resendApiKey }}
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.ollamaApiKey }}
  OLLAMA_API_KEY: {{ .Values.secrets.ollamaApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.clerkSecretKey }}
  CLERK_SECRET_KEY: {{ .Values.auth.clerkSecretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.licenceSecret }}
  LICENCE_SECRET: {{ .Values.secrets.licenceSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpPassword }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | b64enc | quote }}
  {{- end }}
