"""SAP-specific synonym / alias tables.

All tables map a surface form (lowercased, whitespace-collapsed) to its
canonical SAP representation. Tables are intentionally exhaustive for the
forms that appear in real customer data — additions over time are expected.

Nothing here performs I/O.
"""

from __future__ import annotations

# ─── Legal-entity suffixes (stripped during name similarity) ─────────────────
#
# Sorted longest-first so the stripper matches "pvt ltd" before "ltd".
LEGAL_SUFFIXES: tuple[str, ...] = (
    "private limited",
    "incorporated",
    "limited liability company",
    "limited partnership",
    "limited",
    "gesellschaft mit beschrankter haftung",
    "aktiengesellschaft",
    "societe anonyme",
    "sociedad anonima",
    "sp. z o.o.",
    "pvt ltd",
    "pvt. ltd.",
    "pty ltd",
    "pty. ltd.",
    "pte ltd",
    "pte. ltd.",
    "s.p.a.",
    "s.r.l.",
    "s.a.s.",
    "s.a.r.l.",
    "s.a.",
    "s.l.",
    "s.r.l",
    "corp.",
    "corp",
    "corporation",
    "company",
    "co.,ltd.",
    "co., ltd.",
    "co.,ltd",
    "co., ltd",
    "co., inc.",
    "co., inc",
    "co.,",
    "co.",
    "co",
    "inc.",
    "inc",
    "llc",
    "l.l.c.",
    "ltd.",
    "ltd",
    "lp",
    "l.p.",
    "llp",
    "l.l.p.",
    "plc",
    "p.l.c.",
    "gmbh",
    "mbh",
    "ag",
    "kg",
    "ohg",
    "bv",
    "nv",
    "ab",
    "as",
    "oy",
    "sa",
    "srl",
    "spa",
    "kk",
    "k.k.",
    "ehf",
    "oao",
    "zao",
)


# ─── ISO 3166-1 country aliases (alpha-2 canonical) ──────────────────────────
#
# Includes alpha-3 codes, common names, historical forms, and SAP shorthands.
COUNTRY_ALIASES: dict[str, str] = {
    # Alpha-3 and common names
    "usa": "US", "united states": "US", "united states of america": "US",
    "u.s.": "US", "u.s.a.": "US", "america": "US", "us": "US",
    "uk": "GB", "united kingdom": "GB", "great britain": "GB", "britain": "GB",
    "england": "GB", "gbr": "GB", "u.k.": "GB", "gb": "GB",
    "deu": "DE", "germany": "DE", "deutschland": "DE", "de": "DE",
    "fra": "FR", "france": "FR", "fr": "FR",
    "ita": "IT", "italy": "IT", "italia": "IT", "it": "IT",
    "esp": "ES", "spain": "ES", "espana": "ES", "es": "ES",
    "nld": "NL", "netherlands": "NL", "holland": "NL", "the netherlands": "NL",
    "nl": "NL",
    "bel": "BE", "belgium": "BE", "be": "BE",
    "che": "CH", "switzerland": "CH", "swiss": "CH", "ch": "CH",
    "aut": "AT", "austria": "AT", "at": "AT",
    "swe": "SE", "sweden": "SE", "se": "SE",
    "nor": "NO", "norway": "NO", "no": "NO",
    "dnk": "DK", "denmark": "DK", "dk": "DK",
    "fin": "FI", "finland": "FI", "fi": "FI",
    "irl": "IE", "ireland": "IE", "ie": "IE",
    "prt": "PT", "portugal": "PT", "pt": "PT",
    "pol": "PL", "poland": "PL", "pl": "PL",
    "cze": "CZ", "czech republic": "CZ", "czechia": "CZ", "cz": "CZ",
    "hun": "HU", "hungary": "HU", "hu": "HU",
    "can": "CA", "canada": "CA", "ca": "CA",
    "mex": "MX", "mexico": "MX", "mx": "MX",
    "bra": "BR", "brazil": "BR", "brasil": "BR", "br": "BR",
    "arg": "AR", "argentina": "AR", "ar": "AR",
    "chl": "CL", "chile": "CL", "cl": "CL",
    "col": "CO", "colombia": "CO", "co": "CO",
    "per": "PE", "peru": "PE", "pe": "PE",
    "ven": "VE", "venezuela": "VE", "ve": "VE",
    "zaf": "ZA", "south africa": "ZA", "rsa": "ZA", "za": "ZA",
    "nga": "NG", "nigeria": "NG", "ng": "NG",
    "egy": "EG", "egypt": "EG", "eg": "EG",
    "ken": "KE", "kenya": "KE", "ke": "KE",
    "mar": "MA", "morocco": "MA", "ma": "MA",
    "chn": "CN", "china": "CN", "p.r.c.": "CN", "prc": "CN", "cn": "CN",
    "hkg": "HK", "hong kong": "HK", "hk": "HK",
    "twn": "TW", "taiwan": "TW", "tw": "TW",
    "jpn": "JP", "japan": "JP", "jp": "JP",
    "kor": "KR", "south korea": "KR", "korea": "KR", "republic of korea": "KR",
    "kr": "KR",
    "ind": "IN", "india": "IN", "bharat": "IN", "in": "IN",
    "pak": "PK", "pakistan": "PK", "pk": "PK",
    "bgd": "BD", "bangladesh": "BD", "bd": "BD",
    "lka": "LK", "sri lanka": "LK", "lk": "LK",
    "idn": "ID", "indonesia": "ID", "id": "ID",
    "mys": "MY", "malaysia": "MY", "my": "MY",
    "sgp": "SG", "singapore": "SG", "sg": "SG",
    "tha": "TH", "thailand": "TH", "th": "TH",
    "vnm": "VN", "vietnam": "VN", "viet nam": "VN", "vn": "VN",
    "phl": "PH", "philippines": "PH", "ph": "PH",
    "aus": "AU", "australia": "AU", "au": "AU",
    "nzl": "NZ", "new zealand": "NZ", "nz": "NZ",
    "rus": "RU", "russia": "RU", "russian federation": "RU", "ru": "RU",
    "ukr": "UA", "ukraine": "UA", "ua": "UA",
    "tur": "TR", "turkey": "TR", "turkiye": "TR", "tr": "TR",
    "sau": "SA", "saudi arabia": "SA", "ksa": "SA", "sa": "SA",
    "are": "AE", "united arab emirates": "AE", "uae": "AE", "ae": "AE",
    "isr": "IL", "israel": "IL", "il": "IL",
    "irn": "IR", "iran": "IR", "ir": "IR",
    "irq": "IQ", "iraq": "IQ", "iq": "IQ",
    "qat": "QA", "qatar": "QA", "qa": "QA",
    "kwt": "KW", "kuwait": "KW", "kw": "KW",
    "jor": "JO", "jordan": "JO", "jo": "JO",
    "lbn": "LB", "lebanon": "LB", "lb": "LB",
}


# ─── ISO 4217 currency aliases ───────────────────────────────────────────────
CURRENCY_ALIASES: dict[str, str] = {
    "us$": "USD", "usd": "USD", "dollar": "USD", "dollars": "USD",
    "american dollar": "USD", "$": "USD", "us dollar": "USD",
    "eur": "EUR", "euro": "EUR", "euros": "EUR", "€": "EUR",
    "gbp": "GBP", "pound": "GBP", "pounds": "GBP", "sterling": "GBP",
    "pound sterling": "GBP", "british pound": "GBP", "£": "GBP",
    "jpy": "JPY", "yen": "JPY", "japanese yen": "JPY", "¥": "JPY",
    "chf": "CHF", "swiss franc": "CHF", "franc": "CHF",
    "cad": "CAD", "canadian dollar": "CAD",
    "aud": "AUD", "australian dollar": "AUD",
    "nzd": "NZD", "new zealand dollar": "NZD",
    "zar": "ZAR", "rand": "ZAR", "south african rand": "ZAR", "r": "ZAR",
    "inr": "INR", "rupee": "INR", "indian rupee": "INR", "rs": "INR",
    "rs.": "INR", "₹": "INR",
    "cny": "CNY", "rmb": "CNY", "yuan": "CNY", "renminbi": "CNY",
    "chinese yuan": "CNY", "人民币": "CNY",
    "hkd": "HKD", "hong kong dollar": "HKD",
    "sgd": "SGD", "singapore dollar": "SGD",
    "krw": "KRW", "won": "KRW", "south korean won": "KRW",
    "thb": "THB", "baht": "THB", "thai baht": "THB",
    "myr": "MYR", "ringgit": "MYR",
    "php": "PHP", "peso": "PHP", "philippine peso": "PHP",
    "idr": "IDR", "rupiah": "IDR",
    "vnd": "VND", "dong": "VND",
    "brl": "BRL", "real": "BRL", "brazilian real": "BRL",
    "mxn": "MXN", "mexican peso": "MXN",
    "ars": "ARS", "argentine peso": "ARS",
    "clp": "CLP", "chilean peso": "CLP",
    "cop": "COP", "colombian peso": "COP",
    "pen": "PEN", "sol": "PEN", "peruvian sol": "PEN",
    "sek": "SEK", "krona": "SEK", "swedish krona": "SEK",
    "nok": "NOK", "norwegian krone": "NOK",
    "dkk": "DKK", "danish krone": "DKK",
    "pln": "PLN", "zloty": "PLN",
    "czk": "CZK", "koruna": "CZK",
    "huf": "HUF", "forint": "HUF",
    "ron": "RON", "leu": "RON",
    "bgn": "BGN", "lev": "BGN",
    "rub": "RUB", "ruble": "RUB", "rouble": "RUB",
    "uah": "UAH", "hryvnia": "UAH",
    "try": "TRY", "lira": "TRY", "turkish lira": "TRY",
    "ils": "ILS", "shekel": "ILS", "israeli shekel": "ILS",
    "aed": "AED", "dirham": "AED", "uae dirham": "AED",
    "sar": "SAR", "riyal": "SAR", "saudi riyal": "SAR",
    "qar": "QAR", "qatari riyal": "QAR",
    "kwd": "KWD", "kuwaiti dinar": "KWD",
    "ngn": "NGN", "naira": "NGN",
    "egp": "EGP", "egyptian pound": "EGP",
    "kes": "KES", "shilling": "KES", "kenyan shilling": "KES",
    "mad": "MAD", "moroccan dirham": "MAD",
}


# ─── SAP Unit of Measure aliases ─────────────────────────────────────────────
#
# SAP uses ISO 2-char or 3-char UoM codes (see T006) — these are the most
# common free-text forms seen in real uploads.
UOM_ALIASES: dict[str, str] = {
    # Count
    "each": "EA", "ea": "EA", "ec": "EA", "pc": "PC", "pcs": "PC",
    "piece": "PC", "pieces": "PC", "st": "ST", "stk": "ST",
    "unit": "UN", "units": "UN", "un": "UN",
    "dozen": "DZ", "dz": "DZ",
    "pair": "PR", "pr": "PR",

    # Weight
    "kg": "KG", "kilogram": "KG", "kilograms": "KG", "kgs": "KG",
    "g": "G", "gram": "G", "grams": "G", "gr": "G", "gm": "G",
    "lb": "LB", "lbs": "LB", "pound": "LB", "pounds": "LB",
    "oz": "OZ", "ounce": "OZ", "ounces": "OZ",
    "t": "TO", "ton": "TO", "tons": "TO", "tonne": "TO", "tonnes": "TO",
    "to": "TO", "mt": "TO", "metric ton": "TO",

    # Length
    "mm": "MM", "millimeter": "MM", "millimetre": "MM", "millimeters": "MM",
    "cm": "CM", "centimeter": "CM", "centimetre": "CM", "centimeters": "CM",
    "m": "M", "meter": "M", "metre": "M", "meters": "M", "metres": "M",
    "km": "KM", "kilometer": "KM", "kilometre": "KM",
    "in": "IN", "inch": "IN", "inches": "IN",
    "ft": "FT", "foot": "FT", "feet": "FT",
    "yd": "YD", "yard": "YD", "yards": "YD",
    "mi": "MI", "mile": "MI", "miles": "MI",

    # Volume
    "ml": "ML", "milliliter": "ML", "millilitre": "ML",
    "l": "L", "liter": "L", "litre": "L", "liters": "L", "litres": "L",
    "lt": "L",
    "m3": "M3", "cubic meter": "M3", "cubic metre": "M3", "cbm": "M3",
    "gal": "GAL", "gallon": "GAL", "gallons": "GAL",
    "oz(fl)": "FOZ", "fluid ounce": "FOZ", "fl oz": "FOZ",

    # Area
    "m2": "M2", "sqm": "M2", "square meter": "M2", "square metre": "M2",
    "ft2": "FT2", "sqft": "FT2", "square foot": "FT2",

    # Time
    "h": "HR", "hr": "HR", "hour": "HR", "hours": "HR",
    "min": "MIN", "minute": "MIN", "minutes": "MIN",
    "s": "SEC", "sec": "SEC", "second": "SEC", "seconds": "SEC",
    "d": "DAY", "day": "DAY", "days": "DAY",
    "wk": "WK", "week": "WK", "weeks": "WK",
    "mo": "MON", "month": "MON", "months": "MON", "mon": "MON",
    "yr": "YR", "year": "YR", "years": "YR",
}


# ─── Common business-name abbreviations (pre-similarity expansion) ───────────
BUSINESS_ABBR: dict[str, str] = {
    "&": "and",
    "+": "and",
    "co": "company",
    "intl": "international",
    "int'l": "international",
    "mfg": "manufacturing",
    "tech": "technology",
    "techn": "technology",
    "grp": "group",
    "assoc": "associates",
    "bros": "brothers",
    "ent": "enterprises",
    "ind": "industries",
    "indl": "industrial",
    "natl": "national",
    "svcs": "services",
    "svc": "service",
    "sys": "systems",
    "sol": "solutions",
    "solns": "solutions",
    "st": "saint",
    "mt": "mount",
}
